# media_census.ps1 - the vetted-vs-placeholder ledger, and the clean-break switch.
#
# The provenance manifest (assets\photos\_media-manifest.json, written by
# sync_sales_tools.ps1 from Tyler's SALES TOOLS library) is the ONE arbiter:
# a photo is VETTED if and only if it is in the manifest. Everything else under
# assets\photos\ is placeholder ("old guard"), except shop-* folders (live-build
# carousels, owned by the shop-live pipeline - never touched here).
#
# Modes:
#   (default)           census: per-slug vetted/placeholder table, hardcoded-page
#                       references to placeholder files, and the Tyler-owes list.
#                       Writes _build\media-census.md and prints to console.
#   -Baseline           also snapshot every CURRENT placeholder file to
#                       _build\media-oldguard-baseline.json (refuses to overwrite
#                       an existing baseline unless -Force).
#   -Purge              DRY RUN of the clean break: list exactly what would be
#                       deleted. Deletes nothing.
#   -Purge -ReallyDelete THE CLEAN BREAK: delete every placeholder photo (web +
#                       thumb) from assets\photos\, then regenerate the gallery
#                       (build_gallery.pl), restamp assets, and run the link
#                       audit so every page that referenced a purged file is
#                       REPORTED. Git history keeps the files; nothing is lost.
#
# Never touches: Tyler's SALES TOOLS (not even read), shop-* folders, anything
# in the manifest, anything outside assets\photos\.
# KEEP THIS FILE ASCII-ONLY - Windows PowerShell 5.1.

param(
  [switch]$Baseline,
  [switch]$Force,
  [switch]$Purge,
  [switch]$ReallyDelete
)

$ErrorActionPreference = 'Stop'
$BuildDir = Split-Path $MyInvocation.MyCommand.Path -Parent
$Root     = Split-Path $BuildDir -Parent
$PhotoDir = Join-Path $Root 'assets\photos'
$Perl     = 'C:\Program Files\Git\usr\bin\perl.exe'

$manifestPath = Join-Path $PhotoDir '_media-manifest.json'
if (-not (Test-Path -LiteralPath $manifestPath)) { throw "No manifest at $manifestPath - run sync_sales_tools.ps1 first." }
$manifest = Get-Content -LiteralPath $manifestPath -Raw -Encoding UTF8 | ConvertFrom-Json
$vetted = @{}
foreach ($p in $manifest.entries.PSObject.Properties) { $vetted[$p.Name.ToLower()] = $true }

# ---------- walk assets\photos ----------
$slugStats = @{}
$placeholders = New-Object System.Collections.ArrayList
foreach ($slugDir in Get-ChildItem -LiteralPath $PhotoDir -Directory) {
  if ($slugDir.Name -like 'shop-*') { continue }
  $slug = $slugDir.Name
  $st = @{ vetted = 0; ph = 0; phBytes = [long]0 }
  foreach ($f in Get-ChildItem -LiteralPath $slugDir.FullName -File -Recurse) {
    if ($f.Extension -notmatch '(?i)^\.jpe?g$') { continue }
    $isThumb = ($f.DirectoryName -like '*\thumbs')
    $key = ($slug + '/' + $f.Name).ToLower()
    if ($vetted[$key]) {
      if (-not $isThumb) { $st.vetted = $st.vetted + 1 }
    } else {
      if (-not $isThumb) { $st.ph = $st.ph + 1 }
      $st.phBytes = $st.phBytes + $f.Length
      $rel = $f.FullName.Substring($PhotoDir.Length + 1)
      [void]$placeholders.Add(@{ rel = $rel; bytes = $f.Length; slug = $slug; thumb = $isThumb })
    }
  }
  $slugStats[$slug] = $st
}

# ---------- hardcoded page references to placeholder files ----------
$refHits = New-Object System.Collections.ArrayList
$pages = Get-ChildItem -LiteralPath $Root -Filter *.html -File -Recurse |
  Where-Object { $_.FullName -notmatch '\\PHOTO PATHWAYS\\' } |
  Where-Object { $_.FullName -notlike (Join-Path $Root 'photos\index.html') }
  # photos\index.html is wholly generated by build_gallery.pl and regenerates in
  # the purge chain - its references self-heal, so listing them is noise.
foreach ($pg in $pages) {
  $txt = [IO.File]::ReadAllText($pg.FullName)
  foreach ($m in [regex]::Matches($txt, 'assets/photos/([A-Za-z0-9\-]+)/(?:thumbs/)?([^"''\s\)\?]+\.jpe?g)')) {
    $slug = $m.Groups[1].Value
    if ($slug -like 'shop-*') { continue }
    $key = ($slug + '/' + $m.Groups[2].Value).ToLower()
    if (-not $vetted[$key]) {
      $relPage = $pg.FullName.Substring($Root.Length + 1)
      [void]$refHits.Add(($relPage + '  ->  ' + $slug + '/' + $m.Groups[2].Value))
    }
  }
}
$refHits = @($refHits | Sort-Object -Unique)

# ---------- report ----------
# manual sums: PS 5.1 Measure-Object -Property cannot read hashtable keys
$phBytesTotal = [long]0
foreach ($p in $placeholders) { $phBytesTotal = $phBytesTotal + $p.bytes }
$phMB = [math]::Round($phBytesTotal / 1MB, 1)
$L = New-Object System.Collections.ArrayList
[void]$L.Add('# MEDIA CENSUS - vetted vs placeholder')
[void]$L.Add('')
[void]$L.Add(('Generated {0} by _build\media_census.ps1. The manifest is the arbiter:' -f (Get-Date -Format 'yyyy-MM-dd HH:mm')))
[void]$L.Add('vetted = in Tylers SALES TOOLS provenance manifest. shop-* folders exempt.')
[void]$L.Add('')
[void]$L.Add('| Gallery | Vetted | Placeholder |')
[void]$L.Add('|---|---|---|')
foreach ($slug in ($slugStats.Keys | Sort-Object)) {
  $s = $slugStats[$slug]
  [void]$L.Add(('| {0} | {1} | {2} |' -f $slug, $s.vetted, $s.ph))
}
$totV = 0; $totP = 0
foreach ($s in $slugStats.Values) { $totV = $totV + $s.vetted; $totP = $totP + $s.ph }
[void]$L.Add(('| **TOTAL** | **{0}** | **{1}** ({2} MB incl. thumbs) |' -f $totV, $totP, $phMB))
[void]$L.Add('')
[void]$L.Add('## What Tyler still owes (galleries with ZERO vetted photos)')
$owes = @($slugStats.Keys | Where-Object { $slugStats[$_].vetted -eq 0 -and $slugStats[$_].ph -gt 0 } | Sort-Object)
if ($owes.Count) { foreach ($o in $owes) { [void]$L.Add(('- {0} ({1} placeholder photos carrying the gallery)' -f $o, $slugStats[$o].ph)) } }
else { [void]$L.Add('- none - every gallery has at least one vetted photo') }
[void]$L.Add('')
[void]$L.Add('## Pages hardcoding placeholder files (break on purge until re-pointed or re-shot)')
if ($refHits.Count) { foreach ($r in $refHits) { [void]$L.Add('- ' + $r) } }
else { [void]$L.Add('- none - every hardcoded photo reference is vetted') }
[void]$L.Add('')
$reportPath = Join-Path $BuildDir 'media-census.md'
[IO.File]::WriteAllLines($reportPath, $L, (New-Object System.Text.UTF8Encoding($false)))
$L | ForEach-Object { Write-Output $_ }
Write-Output ('report written: ' + $reportPath)

# ---------- baseline snapshot ----------
if ($Baseline) {
  $basePath = Join-Path $BuildDir 'media-oldguard-baseline.json'
  if ((Test-Path -LiteralPath $basePath) -and -not $Force) {
    Write-Output 'BASELINE ALREADY EXISTS - not overwriting (use -Force to replace).'
  } else {
    $snap = @{ taken = (Get-Date -Format 'o'); note = 'every placeholder file under assets\photos at snapshot time; git history holds the bytes'; files = $placeholders }
    ($snap | ConvertTo-Json -Depth 5) | Out-File -LiteralPath $basePath -Encoding utf8
    Write-Output ('baseline written: ' + $basePath + ' (' + $placeholders.Count + ' files)')
  }
}

# ---------- the clean break ----------
if ($Purge) {
  Write-Output ''
  Write-Output ('PURGE: {0} placeholder files ({1} MB) would be deleted from assets\photos.' -f $placeholders.Count, $phMB)
  if (-not $ReallyDelete) {
    Write-Output 'DRY RUN - nothing deleted. Re-run with -Purge -ReallyDelete to execute the clean break.'
    Write-Output ('NOTE: {0} hardcoded page reference(s) above will break and must be re-pointed after the purge.' -f $refHits.Count)
  } else {
    $gone = 0
    foreach ($p in $placeholders) {
      Remove-Item -LiteralPath (Join-Path $PhotoDir $p.rel) -Force
      $gone = $gone + 1
    }
    Write-Output ('DELETED {0} files. Regenerating gallery, restamping, auditing...' -f $gone)
    Push-Location -LiteralPath $Root
    try {
      & $Perl '_build/build_gallery.pl'
      & $Perl '_build/stamp_assets.pl'
      & $Perl '_build/audit_links.pl'
    } finally { Pop-Location }
    Write-Output ''
    Write-Output 'CLEAN BREAK DONE. Review the audit output above for newly-broken references,'
    Write-Output 'commit, and push. Recovery if ever needed: the files live in git history.'
  }
}
