/* SPEC_DATA.js - GENERATED by _build/gen_spec_data.ps1 from the shop spec
   worksheets (WB FILES\2 - SHOP AND TECHNICAL\SPEC WORKSHEETS). CONFIRMED figures
   only: DERIVED / UNCONFIRMED / QUERY values are excluded at generation.
   Do not hand-edit - correct the worksheet and re-run. SPEC-01 / TOOL-04. */
const WB_SPEC_GROUPS = [
  ["Dimensions", [["length","Length"],["loa","Length overall"],["beam","Beam"],["floorWidth","Interior floor width"],["sideHeight","Side height"],["intSideHeight","Interior side height"],["bottomWidth","Bottom width"]]],
  ["Construction", [["bottomGauge","Bottom gauge"],["bottomGaugeCenter","Bottom gauge, center"],["sideGauge","Side gauge"],["deltaPadGauge","Delta pad gauge"]]],
  ["Weight & fuel", [["weightOpen","Weight (open)"],["weightWS","Weight (w/ windshield)"],["fuel","Fuel tank"]]],
  ["Power", [["maxPropHP","Max prop HP"],["maxJetHP","Max jet HP"],["maxTillerHP","Max tiller HP"],["stdMotor","Standard motor"],["stdJet","Standard jet"]]],
  ["Deadrise", [["deadrise","Constant deadrise"],["deadriseTransom","At transom"],["deadriseVee","At vee transition"],["deadriseBow","At bow"]]]
];
const WB_SPECS = {
  "ak": {
    "18": {"length":"18'9\"","loa":"20'1\" (w/ pods)","beam":"82\"","sideHeight":"28\"","bottomWidth":"66\"","bottomGauge":"1/8\"","bottomGaugeCenter":"1/4\"","sideGauge":"1/8\"","weightOpen":"1,175 lbs","weightWS":"1,250 lbs","fuel":"36 gal","maxPropHP":"115","maxJetHP":"200","deadrise":"9 deg"},
    "20": {"length":"20'9\"","loa":"20'9\"","beam":"82\"","sideHeight":"28\"","bottomWidth":"66\"","bottomGauge":"1/8\"","bottomGaugeCenter":"1/4\"","sideGauge":"1/8\"","weightOpen":"1,255 lbs","weightWS":"1,330 lbs","fuel":"50 gal","maxPropHP":"140","maxJetHP":"250","deadrise":"9 deg"}
  },
  "lt": {
    "16": {"length":"16'8\"","loa":"16'8\"","beam":"80\"","sideHeight":"21\"","bottomWidth":"60\"","bottomGauge":"1/8\"","sideGauge":"1/8\"","weightOpen":"690 lbs","fuel":"15 gal (optional)","maxPropHP":"60","maxJetHP":"90","maxTillerHP":"60","deadrise":"9 deg"},
    "18": {"length":"18'8\"","loa":"20'1\" (w/ swimstep)","beam":"80\"","sideHeight":"21\"","bottomWidth":"60\"","bottomGauge":"1/8\"","sideGauge":"1/8\"","weightOpen":"740 lbs","fuel":"15 gal (optional)","maxPropHP":"70","maxJetHP":"115","maxTillerHP":"115","deadrise":"9 deg"},
    "20": {"length":"20'8\"","loa":"20'8\"","beam":"80\"","sideHeight":"21\"","bottomWidth":"60\"","bottomGauge":"1/8\"","sideGauge":"1/8\"","weightOpen":"800 lbs","fuel":"15 gal (optional)","maxPropHP":"70","maxJetHP":"115","maxTillerHP":"140","deadrise":"9 deg"}
  },
  "rogue": {
    "16": {"length":"16'","loa":"17'11\"","beam":"85\"","sideHeight":"28\"","bottomWidth":"60\"","bottomGauge":"1/2\"","sideGauge":"1/2\"","weightOpen":"890 lbs","fuel":"14 gal","maxPropHP":"60","maxJetHP":"115","deadrise":"9 deg"},
    "18": {"length":"18'","loa":"20'2\"","beam":"86\"","sideHeight":"32\"","bottomWidth":"66\"","bottomGauge":"1/2\"","sideGauge":"1/2\"","weightOpen":"1,150 lbs","fuel":"14 gal","maxPropHP":"115","maxJetHP":"200","deadrise":"9 deg"},
    "20": {"length":"20'","loa":"21'11\"","beam":"86\"","sideHeight":"32\"","bottomWidth":"66\"","bottomGauge":"5/8\"","sideGauge":"1/2\"","weightOpen":"1,350 lbs","fuel":"26 gal","maxPropHP":"115","maxJetHP":"250","deadrise":"9 deg"}
  },
  "scout": {
    "19": {"length":"19'9\"","loa":"21'9\"","beam":"98\"","sideHeight":"34\"","bottomWidth":"72\"","bottomGauge":".190\"","sideGauge":".125\"","deltaPadGauge":".500\"","fuel":"50 gal","stdMotor":"5.3DI","stdJet":"214 (Hamilton)","deadriseTransom":"10 deg","deadriseBow":"17 deg"},
    "21": {"length":"21'9\"","loa":"23'9\"","beam":"98\"","sideHeight":"34\"","bottomWidth":"72\"","bottomGauge":".190\"","sideGauge":".125\"","deltaPadGauge":".500\"","fuel":"50 gal","stdMotor":"5.3DI","stdJet":"214 (Hamilton)","deadriseTransom":"10 deg","deadriseBow":"17 deg"},
    "23": {"length":"23'9\"","loa":"25'9\"","beam":"98\"","sideHeight":"34\"","bottomWidth":"72\"","bottomGauge":".190\"","sideGauge":".125\"","deltaPadGauge":".500\"","fuel":"50 gal","stdMotor":"5.3DI","stdJet":"214 (Hamilton)","deadriseTransom":"10 deg","deadriseBow":"17 deg"}
  },
  "scoutwb": {
    "21": {"stdMotor":"6.2DI"},
    "23": {"stdMotor":"6.2DI"},
    "25": {"stdMotor":"6.2DI"}
  },
  "skagit": {
    "18": {"length":"18'","loa":"20'5\" (w/ pods)","beam":"93\"","floorWidth":"76\"","sideHeight":"34\"","intSideHeight":"26\"","bottomWidth":"72\"","bottomGauge":".190\"","sideGauge":".125\"","weightOpen":"1,325 lbs","weightWS":"1,400 lbs","fuel":"50 gal","maxPropHP":"115","maxJetHP":"200","deadriseTransom":"10 deg"},
    "20": {"length":"20'","loa":"20'10\"","beam":"93\"","floorWidth":"76\"","sideHeight":"34\"","intSideHeight":"26\"","bottomWidth":"72\"","bottomGauge":".190\"","sideGauge":".125\"","weightOpen":"1,425 lbs","weightWS":"1,500 lbs","fuel":"50 gal","maxPropHP":"140","maxJetHP":"250","deadriseTransom":"10 deg"}
  },
  "skagitib": {
    "18": {"length":"18'","loa":"20'5\" (w/ swimstep)","beam":"93\"","floorWidth":"76\"","sideHeight":"34\"","intSideHeight":"26\"","bottomWidth":"72\"","bottomGauge":".190\"","sideGauge":".125\"","fuel":"50 gal","maxPropHP":"NA","maxJetHP":"NA","deadriseTransom":"10 deg"},
    "20": {"length":"20'","loa":"20'10\"","beam":"93\"","floorWidth":"76\"","sideHeight":"34\"","intSideHeight":"26\"","bottomWidth":"72\"","bottomGauge":".190\"","sideGauge":".125\"","fuel":"50 gal","maxPropHP":"NA","maxJetHP":"NA","deadriseTransom":"10 deg"}
  },
  "skagitx": {
    "21": {"length":"21 ft","loa":"23 ft 6 in","beam":"90 in","floorWidth":"76 in","sideHeight":"29.5 in","intSideHeight":"21.5 in","bottomWidth":"72 in","bottomGauge":".190 in","sideGauge":".125 in","weightWS":"3,400 lb","fuel":"50 gal","stdMotor":"5.3DI","stdJet":"214 or SD309","deadriseTransom":"10 deg"}
  },
  "so": {
    "18": {"length":"18'","loa":"20'5\" (w/ bracket)","beam":"98\"","sideHeight":"34\"","bottomWidth":"78\"","bottomGauge":".190\"","sideGauge":".125\"","weightWS":"1,830 lbs","fuel":"52 gal","maxPropHP":"150","maxJetHP":"N/A - prop only","deadriseTransom":"16 deg","deadriseBow":"30 deg"},
    "20": {"length":"20'","loa":"22'5\" (w/ bracket)","beam":"98\"","sideHeight":"34\"","bottomWidth":"78\"","bottomGauge":".190\"","sideGauge":".125\"","weightWS":"1,940 lbs","fuel":"52 gal","maxPropHP":"200","maxJetHP":"N/A - prop only","deadriseTransom":"16 deg","deadriseBow":"30 deg"}
  },
  "sport": {
    "18": {"length":"18'6\"","loa":"20'1\" (w/ pods)","beam":"94\"","floorWidth":"78\"","sideHeight":"32\"","intSideHeight":"25\"","bottomWidth":"72\"","bottomGauge":".190\"","sideGauge":".125\"","weightOpen":"1,325 lbs","weightWS":"1,400 lbs","fuel":"50 gal","maxPropHP":"115","maxJetHP":"200","deadriseTransom":"10 deg","deadriseBow":"18 deg"},
    "20": {"length":"20'6\"","loa":"20'6\"","beam":"94\"","floorWidth":"78\"","sideHeight":"32\"","intSideHeight":"25\"","bottomWidth":"72\"","bottomGauge":".190\"","sideGauge":".125\"","weightOpen":"1,425 lbs","weightWS":"1,500 lbs","fuel":"50 gal","maxPropHP":"140","maxJetHP":"250","deadriseTransom":"10 deg","deadriseBow":"18 deg"}
  },
  "sportib": {

  },
  "sportster": {
    "21": {"length":"21'","loa":"21'8\"","beam":"106\"","floorWidth":"NA","sideHeight":"30\"","intSideHeight":"NA","bottomWidth":"88\"","bottomGauge":"3/16\"","sideGauge":"1/8\"","weightOpen":"1,805 lbs","weightWS":"1,905 lbs","fuel":"52 gal","maxPropHP":"200","maxJetHP":"250","maxTillerHP":"250","deadriseTransom":"12 deg","deadriseBow":"18 deg"},
    "23": {"length":"23'","loa":"23'8\"","beam":"106\"","floorWidth":"NA","sideHeight":"30\"","intSideHeight":"NA","bottomWidth":"88\"","bottomGauge":"3/16\"","sideGauge":"1/8\"","weightOpen":"1,905 lbs","weightWS":"2,005 lbs","fuel":"52 gal","maxPropHP":"225","maxJetHP":"250","maxTillerHP":"250","deadriseTransom":"12 deg","deadriseBow":"18 deg"},
    "25": {"length":"25'","loa":"25'8\"","beam":"106\"","floorWidth":"NA","sideHeight":"30\"","intSideHeight":"NA","bottomWidth":"88\"","bottomGauge":"3/16\"","sideGauge":"1/8\"","weightOpen":"2,005 lbs","weightWS":"2,105 lbs","fuel":"52 gal","maxPropHP":"225","maxJetHP":"250","maxTillerHP":"250","deadriseTransom":"12 deg","deadriseBow":"18 deg"}
  },
  "ssd": {
    "21": {"length":"21'","beam":"102\"","floorWidth":"NA","sideHeight":"28\"","intSideHeight":"NA","bottomWidth":"84\"","bottomGauge":"3/16\"","sideGauge":"1/8\"","weightOpen":"1,530 lbs","weightWS":"1,630 lbs","fuel":"52 gal","maxPropHP":"200","maxJetHP":"250","maxTillerHP":"250","deadriseTransom":"10 deg","deadriseVee":"14 deg","deadriseBow":"18 deg"},
    "23": {"length":"23'","loa":"23'3\"","beam":"102\"","floorWidth":"NA","sideHeight":"28\"","intSideHeight":"NA","bottomWidth":"84\"","bottomGauge":"3/16\"","sideGauge":"1/8\"","weightOpen":"1,630 lbs","weightWS":"1,730 lbs","fuel":"52 gal","maxPropHP":"225","maxJetHP":"250","maxTillerHP":"250","deadriseTransom":"10 deg","deadriseVee":"14 deg","deadriseBow":"18 deg"},
    "25": {"length":"25'","loa":"25'3\"","beam":"102\"","floorWidth":"NA","sideHeight":"28\"","intSideHeight":"NA","bottomWidth":"84\"","bottomGauge":"3/16\"","sideGauge":"1/8\"","weightOpen":"1,730 lbs","weightWS":"1,830 lbs","fuel":"52 gal","maxPropHP":"225","maxJetHP":"250","maxTillerHP":"250","deadriseTransom":"10 deg","deadriseVee":"14 deg","deadriseBow":"18 deg"}
  },
  "ssdib": {
    "21": {"length":"21'","beam":"102\"","floorWidth":"NA","sideHeight":"28\"","intSideHeight":"NA","bottomWidth":"84\"","bottomGauge":"3/16\"","sideGauge":"1/8\"","maxPropHP":"NA","maxJetHP":"NA","deadriseTransom":"10 deg","deadriseVee":"14 deg","deadriseBow":"18 deg"},
    "23": {"length":"23'","loa":"23'3\"","beam":"102\"","floorWidth":"NA","sideHeight":"28\"","intSideHeight":"NA","bottomWidth":"84\"","bottomGauge":"3/16\"","sideGauge":"1/8\"","weightOpen":"2,760 lbs","weightWS":"2,860 lbs","maxPropHP":"NA","maxJetHP":"NA","deadriseTransom":"10 deg","deadriseVee":"14 deg","deadriseBow":"18 deg"},
    "25": {"length":"25'","loa":"25'3\"","beam":"102\"","floorWidth":"NA","sideHeight":"28\"","intSideHeight":"NA","bottomWidth":"84\"","bottomGauge":"3/16\"","sideGauge":"1/8\"","weightOpen":"2,860 lbs","weightWS":"2,960 lbs","maxPropHP":"NA","maxJetHP":"NA","deadriseTransom":"10 deg","deadriseVee":"14 deg","deadriseBow":"18 deg"}
  },
  "sso": {

  },
  "xl": {
    "20": {"length":"20'7\"","loa":"20'7\"","beam":"99\"","sideHeight":"29.5\"","bottomWidth":"80\"","bottomGauge":".160\"","sideGauge":"1/8\"","weightOpen":"1,250 lbs","weightWS":"1,350 lbs","fuel":"50 gal","maxPropHP":"150","maxJetHP":"300","maxTillerHP":"200","deadrise":"9 deg"}
  },
  "xlib": {

  },
  "xlt": {
    "18": {"length":"18'","loa":"20' (w/ pods)","beam":"93\"","sideHeight":"26\"","bottomWidth":"72\"","bottomGauge":"1/8\"","sideGauge":"1/8\"","weightOpen":"1,080 lbs","fuel":"see price sheet (3 tank options)","maxPropHP":"90","maxJetHP":"200","deadrise":"9 deg"},
    "20": {"length":"20'","loa":"20'10\"","beam":"93\"","sideHeight":"26\"","bottomWidth":"72\"","bottomGauge":"1/8\"","sideGauge":"1/8\"","weightOpen":"1,160 lbs","fuel":"see price sheet (3 tank options)","maxPropHP":"115","maxJetHP":"250","deadrise":"9 deg"}
  }
};
